   <header class="header fixed">
            <div class="header-wrapper">
                <div class="container">

                    <!-- Logo -->
                    <div class="logo">
                        <a href="index-2.html"><img src="assets/img/logo-bella-shop.png" alt="Bella Shop" /></a>
                    </div>
                    <!-- /Logo -->

                    <!-- Header search -->
                    <div class="header-search">
                        <input class="form-control" type="text" placeholder="What are you looking?" />
                        <button><i class="fa fa-search"></i></button>
                    </div>
                    <!-- /Header search -->

                    <!-- Header shopping cart -->
                    <div class="header-cart">
                        <div class="cart-wrapper">
                            <a href="wishlist.html" class="btn btn-theme-transparent hidden-xs hidden-sm"><i
                                    class="fa fa-heart"></i></a>
                            <a href="compare-products.html" class="btn btn-theme-transparent hidden-xs hidden-sm"><i
                                    class="fa fa-exchange"></i></a>
                            <a href="#" class="btn btn-theme-transparent" data-toggle="modal"
                                data-target="#popup-cart"><i class="fa fa-shopping-cart"></i> <span class="hidden-xs"> 0
                                    item(s) - $0.00 </span> <i class="fa fa-angle-down"></i></a>
                            <!-- Mobile menu toggle button -->
                            <a href="#" class="menu-toggle btn btn-theme-transparent"><i class="fa fa-bars"></i></a>
                            <!-- /Mobile menu toggle button -->
                        </div>
                    </div>
                    <!-- Header shopping cart -->

                </div>
            </div>
            <div class="navigation-wrapper">
                <div class="container">
                    <!-- Navigation -->
                    <nav class="navigation closed clearfix">
                        <a href="#" class="menu-toggle-close btn"><i class="fa fa-times"></i></a>
                        <ul class="nav sf-menu">
                            <li class="active"><a href="index-2.html">Homepage</a>
                              
                            </li>
                            <li><a href="category.html">Shop</a>
                                <ul>
                                    <li><a href="category.html">Shop Sidebar Left</a></li>
                                    <li><a href="category-right.html">Shop Sidebar Right</a></li>
                                    <li><a href="category-list.html">Shop List View</a></li>
                                    <li><a href="product-details.html">Product Page</a></li>
                                </ul>
                            </li>
                            <li><a href="#">Blog</a>
                                <ul>
                                    <li><a href="blog.html">Blog Sidebar Left </a></li>
                                    <li><a href="blog-right.html">Blog Sidebar Right</a></li>
                                    <li><a href="blog-post.html">Blog Single Post</a></li>
                                </ul>
                            </li>
                            <li><a href="portfolio.html">Portfolio</a>
                                <ul>
                                    <li><a href="portfolio.html">Portfolio 3 columns</a></li>
                                    <li><a href="portfolio-4col.html">Portfolio 4 columns</a></li>
                                    <li><a href="portfolio-alt.html">Portfolio Alternate</a></li>
                                    <li><a href="portfolio-single.html">Portfolio Single</a></li>
                                </ul>
                            </li>
                           
                            <li><a href="category.html">Men</a></li>
                            <li><a href="category.html">Women</a></li>
                            <li><a href="category.html">Kids</a></li>
                            <li><a href="category.html">New</a></li>
                            <li class="sale"><a href="category.html">Sale</a></li>
                            <li><a href="contact.html">Contact</a></li>
                        </ul>
                    </nav>
                    <!-- /Navigation -->
                </div>
            </div>
        </header>