   <header class="header fixed">
            <div class="header-wrapper">
                <div class="container">

                    <!-- Logo -->
                    <div class="logo">
                        <a href="index-2.html"><img src="assets/img/logo-bella-shop.png" alt="Bella Shop" /></a>
                    </div>
                    <!-- /Logo -->

                    <!-- Header search -->
                    <div class="header-search">
                        <input class="form-control" type="text" placeholder="What are you looking?" />
                        <button><i class="fa fa-search"></i></button>
                    </div>
                    <!-- /Header search -->

                    <!-- Header shopping cart -->
                    <div class="header-cart">
                        <div class="cart-wrapper">
                            <a href="wishlist.html" class="btn btn-theme-transparent hidden-xs hidden-sm"><i
                                    class="fa fa-heart"></i></a>
                            <a href="compare-products.html" class="btn btn-theme-transparent hidden-xs hidden-sm"><i
                                    class="fa fa-exchange"></i></a>
                            <a href="#" class="btn btn-theme-transparent" data-toggle="modal"
                                data-target="#popup-cart"><i class="fa fa-shopping-cart"></i> <span class="hidden-xs"> 0
                                    item(s) - $0.00 </span> <i class="fa fa-angle-down"></i></a>
                            <!-- Mobile menu toggle button -->
                            <a href="#" class="menu-toggle btn btn-theme-transparent"><i class="fa fa-bars"></i></a>
                            <!-- /Mobile menu toggle button -->
                        </div>
                    </div>
                    <!-- Header shopping cart -->

                </div>
            </div>
            <div class="navigation-wrapper">
                <div class="container">
                    <!-- Navigation -->
                    <nav class="navigation closed clearfix">
                        <a href="#" class="menu-toggle-close btn"><i class="fa fa-times"></i></a>
                        <ul class="nav sf-menu">
                            <li class="active"><a href="index-2.html">Homepage</a>
                                <ul>
                                    <li><a href="index-2.html">Homepage 1</a></li>
                                    <li><a href="index-3.html">Homepage 2</a></li>
                                    <li><a href="index-4.html">Homepage 3</a></li>
                                    <li><a href="index-5.html">Homepage 4</a></li>
                                    <li><a href="index-6.html">Homepage 5</a></li>
                                    <li><a href="index-7.html">Homepage 6</a></li>
                                    <li><a href="index-8.html">Homepage 7</a></li>
                                    <li><a href="index-9.html">Homepage 8</a></li>
                                    <li><a href="index-10.html">Homepage 9</a></li>
                                </ul>
                            </li>
                            <li><a href="category.html">Shop</a>
                                <ul>
                                    <li><a href="category.html">Shop Sidebar Left</a></li>
                                    <li><a href="category-right.html">Shop Sidebar Right</a></li>
                                    <li><a href="category-list.html">Shop List View</a></li>
                                    <li><a href="product-details.html">Product Page</a></li>
                                </ul>
                            </li>
                            <li><a href="#">Blog</a>
                                <ul>
                                    <li><a href="blog.html">Blog Sidebar Left </a></li>
                                    <li><a href="blog-right.html">Blog Sidebar Right</a></li>
                                    <li><a href="blog-post.html">Blog Single Post</a></li>
                                </ul>
                            </li>
                            <li><a href="portfolio.html">Portfolio</a>
                                <ul>
                                    <li><a href="portfolio.html">Portfolio 3 columns</a></li>
                                    <li><a href="portfolio-4col.html">Portfolio 4 columns</a></li>
                                    <li><a href="portfolio-alt.html">Portfolio Alternate</a></li>
                                    <li><a href="portfolio-single.html">Portfolio Single</a></li>
                                </ul>
                            </li>
                            <li class="megamenu"><a href="#">Catalog</a>
                                <ul>
                                    <li class="row">
                                        <div class="col-md-2">
                                            <h4 class="block-title"><span>Watches</span></h4>
                                            <ul>
                                                <li><a href="#">Luxury Watches</a></li>
                                                <li><a href="#">
                                                        Smart Watches</a></li>
                                                <li><a href="#">Sports Watches</a></li>
                                                <li><a href="#">Traditional Watches</a></li>
                                                <li><a href="#">Round Watches</a></li>
                                                <li><a href="#">Diamond Watches</a></li>
                                            </ul>
                                        </div>
                                        <div class="col-md-2">
                                            <h4 class="block-title"><span>Watches Brands</span></h4>
                                            <ul>
                                                <li><a href="#">Rolex</a></li>
                                                <li><a href="#">Ulysse Nardins</a></li>
                                                <li><a href="#">Blancpain</a></li>
                                                <li><a href="#">Giarard Perregaux</a></li>
                                                <li><a href="#">Jaeger-LeCoultre</a></li>
                                                <li><a href="#">Audemars Piguet</a></li>
                                            </ul>
                                        </div>
                                        <div class="col-md-2">
                                            <h4 class="block-title"><span>Pages</span></h4>
                                            <ul>
                                                <li><a href="shortcodes.html"><strong>Shortcodes</strong></a></li>
                                                <li><a href="typography.html"><strong>Typography</strong></a></li>
                                                <li><a href="coming-soon.html"><strong>Coming soon</strong></a></li>
                                                <li><a href="error-page.html"><strong>404 Page</strong></a></li>
                                                <li><a href="about.html"><strong>About</strong></a></li>
                                                <li><a href="login.html"><strong>Login</strong></a></li>
                                            </ul>
                                        </div>
                                        <div class="col-md-2 visible-xs">
                                            <h4 class="block-title"><span>My Account</span></h4>
                                            <ul>
                                                <li><a href="accountinformation.html"> Account Information </a></li>
                                                <li><a href="myaccount.html">My Account</a></li>
                                                <li><a href="cng-pw.html">Change Password</a></li>
                                                <li><a href="address-book.html">Address Books</a></li>
                                                <li><a href="order-history.html">Order History</a></li>
                                                <li><a href="review-rating.html">Reviews and Ratings</a></li>
                                                <li><a href="return.html">Returns Requests</a></li>
                                                <li><a href="newsletter.html">Newsletter</a></li>
                                                <li><a href="myaccount-leftsidebar.html">Left Sidebar</a></li>
                                            </ul>
                                        </div>
                                        <div class="col-md-3">
                                            <h4 class="block-title"><span>Header styles</span></h4>
                                            <ul>
                                                <li><a href="index-style-1.html"><strong>Header style 1</strong></a>
                                                </li>
                                                <li><a href="index-style-2.html"><strong>Header style 2</strong></a>
                                                </li>
                                                <li><a href="index-style-3.html"><strong>Header style 3</strong></a>
                                                </li>
                                                <li><a href="index-style-4.html"><strong>Header style 4</strong></a>
                                                </li>
                                                <li><a href="index-style-5.html"><strong>Header style 5</strong></a>
                                                </li>
                                            </ul>
                                        </div>
                                        <div class="col-md-3">
                                            <div class="product-list">
                                                <div class="media">
                                                    <a class="pull-left media-link" href="#">
                                                        <img class="media-object"
                                                            src="assets/img/preview/shop/top-sellers-2.jpg" alt="">
                                                        <i class="fa fa-plus"></i>
                                                    </a>
                                                    <div class="media-body">
                                                        <h4 class="media-heading"><a href="#">Standard Product
                                                                Header</a></h4>
                                                        <div class="rating">
                                                            <span class="star"></span><!--
                                                                --><span class="star active"></span><!--
                                                                --><span class="star active"></span><!--
                                                                --><span class="star active"></span><!--
                                                                --><span class="star active"></span>
                                                        </div>
                                                        <div class="price"><ins>$400.00</ins> <del>$425.00</del></div>
                                                    </div>
                                                </div>
                                                <div class="media">
                                                    <a class="pull-left media-link" href="#">
                                                        <img class="media-object"
                                                            src="assets/img/preview/shop/top-sellers-3.jpg" alt="">
                                                        <i class="fa fa-plus"></i>
                                                    </a>
                                                    <div class="media-body">
                                                        <h4 class="media-heading"><a href="#">Standard Product
                                                                Header</a></h4>
                                                        <div class="rating">
                                                            <span class="star"></span><!--
                                                                --><span class="star active"></span><!--
                                                                --><span class="star active"></span><!--
                                                                --><span class="star active"></span><!--
                                                                --><span class="star active"></span>
                                                        </div>
                                                        <div class="price"><ins>$400.00</ins> <del>$425.00</del></div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </li>
                                </ul>
                            </li>
                            <li><a href="category.html">Men</a></li>
                            <li><a href="category.html">Women</a></li>
                            <li><a href="category.html">Kids</a></li>
                            <li><a href="category.html">New</a></li>
                            <li class="sale"><a href="category.html">Sale</a></li>
                            <li><a href="contact.html">Contact</a></li>
                        </ul>
                    </nav>
                    <!-- /Navigation -->
                </div>
            </div>
        </header>